version: '3.9'

services:
  clickhouse:
    image: clickhouse/clickhouse-server:latest
    container_name: clickhouse-server
    ports:
      - "8123:8123"   # HTTP interface for querying ClickHouse
      - "9000:9000"   # Native protocol for ClickHouse
      - "9440:9440"   # Optional: TLS interface (for secure connections)
    environment:
      CLICKHOUSE_DB: ${CLICKHOUSE_DB}          # Default database from .env file
      CLICKHOUSE_USER: ${CLICKHOUSE_USER}      # User from .env file
      CLICKHOUSE_PASSWORD: ${CLICKHOUSE_PASSWORD} # Password from .env file
    volumes:
      - clickhouse_data:/var/lib/clickhouse
    networks:
      - c8_crons
    healthcheck:
      test: ["CMD", "clickhouse-client", "--query=SELECT 1"]
      interval: 30s
      retries: 3
      start_period: 30s
      timeout: 10s

  airflow:
    image: apache/airflow:2.5.1
    container_name: airflow-server
    depends_on:
      - clickhouse
    ports:
      - "8080:8080"
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION: "false"
      AIRFLOW__CORE__LOAD_EXAMPLES: "false"
      AIRFLOW__WEBSERVER__WORKERS: 2
      AIRFLOW__CORE__SQL_ALCHEMY_CONN: "sqlite:////airflow/airflow.db"
      AIRFLOW__CORE__FERNET_KEY: "YOUR_FERNET_KEY"  # Replace with your Fernet Key
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./plugins:/opt/airflow/plugins
    networks:
      - c8_crons
    restart: always
    command: "airflow standalone"

  zookeeper:
    image: bitnami/zookeeper:latest
    container_name: zookeeper
    ports:
      - "2181:2181"
    networks:
      - c8_crons

  kafka:
    image: bitnami/kafka:latest
    container_name: kafka-server
    ports:
      - "9092:9092"
    environment:
      KAFKA_CFG_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_CFG_LISTENERS: PLAINTEXT://kafka-server:9092,EXTERNAL://0.0.0.0:9092
      KAFKA_CFG_ADVERTISED_LISTENERS: PLAINTEXT://kafka-server:9092,EXTERNAL://localhost:9092
      ALLOW_PLAINTEXT_LISTENER: "yes"
    depends_on:
      - zookeeper
    networks:
      - c8_crons

networks:
  c8_crons:
    driver: bridge

volumes:
  clickhouse_data:
  airflow_logs:
  airflow_dags:
  airflow_plugins:
