version: '3.8'
services:
  clickhouse:
    image: clickhouse/clickhouse-server:latest
    container_name: clickhouse-server
    ports:
      - "8123:8123"   # HTTP interface for querying ClickHouse
      - "9000:9000"   # Native protocol for ClickHouse
      - "9440:9440"   # Optional: TLS interface (for secure connections)
    environment:
      CLICKHOUSE_DB: ${CLICKHOUSE_DB}
      CLICKHOUSE_USER: ${CLICKHOUSE_USER}
      CLICKHOUSE_PASSWORD: ${CLICKHOUSE_PASSWORD}
    volumes:
      - clickhouse_data:/var/lib/clickhouse
    networks:
      - c8_crons
    healthcheck:
      test: ["CMD", "clickhouse-client", "--query=SELECT 1"]
      interval: 30s
      retries: 5
      start_period: 30s
      timeout: 10s

  airflow:
    image: apache/airflow:2.5.1
    container_name: airflow-server
    depends_on:
      clickhouse:
        condition: service_healthy
    ports:
      - "8080:8080"
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION: "false"
      AIRFLOW__CORE__LOAD_EXAMPLES: "false"
      AIRFLOW__WEBSERVER__WORKERS: 2
      AIRFLOW__CORE__SQL_ALCHEMY_CONN: "sqlite:////airflow/airflow.db"
      AIRFLOW__CORE__FERNET_KEY: "YOUR_FERNET_KEY"
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./plugins:/opt/airflow/plugins
    networks:
      - c8_crons
    restart: always
    command: "airflow standalone"
    healthcheck:
      test: ["CMD-SHELL", "curl --fail http://localhost:8080/health || exit 1"]
      interval: 30s
      retries: 5
      start_period: 20s
      timeout: 10s

  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: kafka-server
    hostname: kafka-server
    ports:
      - "9092:9092"
      - "9093:9093"
    environment:
      KAFKA_KRAFT_MODE: "true"  
      KAFKA_PROCESS_ROLES: controller,broker
      KAFKA_NODE_ID: 1
      KAFKA_CONTROLLER_QUORUM_VOTERS: "1@kafka-server:9093"
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-server:9092
      KAFKA_LOG_DIRS: /var/lib/kafka/data
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_LOG_RETENTION_HOURS: 168
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      CLUSTER_ID: "jX3k8fxjRX-b7I9OgYPLQg"  
    volumes:
      - kafka_data:/var/lib/kafka/data
    networks:
      - c8_crons
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "kafka-topics.sh --list --bootstrap-server kafka-server:9092 || exit 1"]
      interval: 30s
      retries: 5
      start_period: 40s
      timeout: 10s

networks:
  c8_crons:
    driver: bridge

volumes:
  clickhouse_data:
    driver: local
  kafka_data:
    driver: local
  airflow_logs:
    driver: local
  airflow_dags:
    driver: local
  airflow_plugins:
    driver: local
